parameters:
  - name: conanConfigUrl
    type: string

steps:
  - bash: |
      echo $(PYTHON) || true
      which $(PYTHON) || true
      $(PYTHON) --version || true
    displayName: Check Python

  - bash: |
      set -e
      $(PYTHON) -m venv .venv
      if ! -d .venv/bin; then
        ln -s "$(Build.SourcesDirectory)/.venv/Scripts" .venv/bin
      fi
    displayName: Create virtualenv

  - bash: |
      set -e
      source .venv/bin/activate
      $(PYTHON) -m pip install --upgrade pip
      $(PYTHON) -m pip install conan
      which conan || true
      conan --version || true
    displayName: Install Conan

  - bash: |
      set -e
      source .venv/bin/activate
      conan config install ${{ parameters.conanConfigUrl }}
      conan profile detect --force
    displayName: Configure Conan
