parameters:
  - name: conanConfigUrl
    type: string

steps:
  - bash: |
      set -e
      python3 -m venv .venv
      if ! [ -d .venv/bin ]; then
        ln -s "$(Build.SourcesDirectory)/.venv/Scripts" .venv/bin
      fi
    displayName: Create virtualenv

  - bash: |
      set -e
      source .venv/bin/activate
      python3 -m pip install --upgrade pip
      python3 -m pip install conan
      conan --version || true
    displayName: Install Conan

  - bash: |
      set -e
      source .venv/bin/activate
      conan config install ${{ parameters.conanConfigUrl }}
      conan profile detect --force
    displayName: Configure Conan

  - bash: |
      set -e
      source .venv/bin/activate
      curl -L -o ".venv/Scripts/jq.exe" https://github.com/jqlang/jq/releases/latest/download/jq-win64.exe
      jq --version || true
    displayName: Install jq
    condition: eq(variables['Agent.OS'], 'Windows_NT')
